export PROJECT = apnaschool
IMPORT_PATH := github.com/ahab94/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
    --link apna-school-mongo-db:apna-school-mongo-db \
    --link apna-school-mysql-db:apna-school-mysql-db \
    ${DEV_IMAGE}
